stages:
  - build

build-debian-package:
  stage: build
  image: debian:latest
  script:
    - apt-get update && apt-get install -y build-essential debhelper
    - dpkg-buildpackage -b -us -uc
    - ls -l ../
    - mkdir result
    - mv ../ddhcpd_* result/
  artifacts:
    paths: 
      - result/*
